In [1]:
# import numpy library
import numpy as np


In [2]:
#dir(np)

In [3]:
#create 1D numpy array
x = np.array([45,67,57,60])
print(x)
print(type(x))
print(x.dtype)

[45 67 57 60]
<class 'numpy.ndarray'>
int32


In [4]:
#verify the data type in array
x = np.array([45,67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

[45.  67.  57.   9.8]
<class 'numpy.ndarray'>
float64


In [6]:
#verify the data type
x = np.array(["A",67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '57' '9.8']
<class 'numpy.ndarray'>
<U32


In [7]:
#xreate a 2D array
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)


In [8]:
#reshaping an array
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [9]:
#create an array with arange()
c = np.arange(3,10)
print(c)
type(c)

[3 4 5 6 7 8 9]


numpy.ndarray

In [12]:
#use of around()
d = np.array([1.3467,3.10987,4.91236])
print(d)
np.around(d,3)

[1.3467  3.10987 4.91236]


array([1.347, 3.11 , 4.912])

In [14]:
#use of np.sqrt()
d = np.array([1.2345,3.13789,4.678])
print(d)
print(np.around(np.sqrt(d),2))

[1.2345  3.13789 4.678  ]
[1.11 1.77 2.16]


In [16]:
#create a 2d array
a1 = np.array([[3,4,5,6],[7,8,2,np.NaN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  6.]
 [ 7.  8.  2. nan]]


dtype('float64')

In [17]:
#use of astype() to convert the data type
a1 = np.array([[3,4,5,6],[7,8,2,np.NaN]])
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '6.0']
 ['7.0' '8.0' '2.0' 'nan']]


dtype('<U32')

In [21]:
#mathematical operations on rows and cols
a2 = np.array([[3,4,5],[6,9,8],[4,6,11]])
a2.sum(axis=1)
a2.sum(axis=0)

array([13, 19, 24])

In [22]:
#matrix operations
a3 = np.array([[3,4,5],[7,8,9],[9,1,6]])
a3

array([[3, 4, 5],
       [7, 8, 9],
       [9, 1, 6]])

In [23]:
a3 = np.array([[3,4,5],[7,8,9],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 8 9]
 [9 1 6]]
[[0 4 5]
 [7 0 9]
 [9 1 0]]


In [24]:
#define two matrices and multipy them
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[8,9]])

#perform matrix multiplication
C = np.matmul(A,B)

In [25]:
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 8]
 [6 9]]


In [26]:
# accessing the array elements
a4 = np.array([[3,4,5],[7,8,9],[9,8,5],[3,4,5]])
a4

array([[3, 4, 5],
       [7, 8, 9],
       [9, 8, 5],
       [3, 4, 5]])

In [27]:
a4[2][0]

9

In [28]:
a4[1:3,0:2]

array([[7, 8],
       [9, 8]])

In [29]:
# accessing max value and its index
a3 = np.array([[3,4,5],[8,9,5],[2,1,7]])
a3

array([[3, 4, 5],
       [8, 9, 5],
       [2, 1, 7]])

In [31]:
#print the index position of max element
print(np.argmax(a3,axis=1))
print(np.argmax(a3,axis=0))

[2 1 2]
[1 1 2]


In [34]:
#print the max value element
print(np.amax(a3,axis=1))
print(np.amax(a3,axis=0))

[5 9 7]
[8 9 7]
